name: sitepap
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.2.11


flutter:
  uses-material-design: true
  assets:
    - web/assets/images/logo.png
    - web/assets/images/appstore1.png
    - web/assets/images/playstore.png
    - web/assets/mockups/01.png
    - web/assets/mockups/02.png
    - web/assets/mockups/03.png
    - web/assets/mockups/04.png
    - web/assets/mockups/05.png


